### ISSUE TITLE
Outreach & communication checklist w/o 2/8

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#10]
* [x] follow up with Alameda pub defenders on clean slate projects
* [x] follow up with SF pub defenders on prop 47
* [x] contact KS of reentry council re community meeting 3/11
