### ISSUE TITLE
Outreach & communication checklist w/o 2/16

### ISSUE THREAD

**Issue by MissPaaj** [codeforamerica/clear-my-record#43]
* [ ] follow up YCL SF PD re redacted rap sheets - LE
* [ ] follow up Alameda PD re clean slate programs
* [ ] track down L of Salvation Army re petitioners - LE
* [x] follow up with SF pub defenders on prop 47 - LE
* [x] follow up KS of reentry council re community meeting 3/11
* [x] Next steps w/ V of Watsonville Law Center - JL
* [x] Ask AR about visiting SFPD clinic hours next Tues - BG
* [ ] follow up Episcopal Charities re upcoming events - LE
* [x] follow up w Adult Probation Services - meet probationers - JL
* [x] try again to schedule with SFDA CM - LE
* [ ] Additional courts contacts thru JMT
